In [1]:
import atomictools as at
import plotly.graph_objects as go
import plotly.io as pio
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import RegularGridInterpolator
pio.renderers.default='iframe'

In [2]:
R = at.R_hydrog(2, 1)
R.plot_R()

In [3]:
val = R.evaluate([6., 2.])
val

array([0.06097646, 0.15018615])

In [4]:
px = at.real_ang_function(1, 1, part="Re")
px.plot_phase()
px2 = at.comb_ang_function(functions=[(1, 1), (1, -1)], coefficients=[-1, 1])
px2.plot_phase()

In [5]:
val = px.evaluate(np.pi/2., 0.*np.pi/2.)
val2 = px2.evaluate(np.pi/2., 0.*np.pi/2.)
np.real(val), np.real(val2)

(0.48860251190291987, 0.4883514758480009)

In [6]:
orb = at.orbital_hydrog(n=2, l=1, m=1, part="Re")
orb.plot_volume()

In [7]:
orb.plot_volume2()

In [1]:
import atomictools as at
import plotly.graph_objects as go
import plotly.io as pio
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import RegularGridInterpolator
pio.renderers.default='iframe'

In [2]:
R = at.R_hydrog(2, 1)
px1 = at.real_ang_function(1, 1, part="Re")
orb1 = at.orbital(R, px1)
orb1.plot_volume()

In [3]:
px2 = at.comb_ang_function(functions=[(1, 1), (1, -1)], coefficients=[-1, 1])
orb2 = at.orbital(R, px2)
orb2.plot_volume()

In [7]:
orb1.evaluate()

array([[[33.47382175, 32.91156951, 32.36990212, ..., 32.36990212,
         32.91156951, 33.47382175],
        [32.91156951, 32.33954348, 31.7881303 , ..., 31.7881303 ,
         32.33954348, 32.91156951],
        [32.36990212, 31.7881303 , 31.22698167, ..., 31.22698167,
         31.7881303 , 32.36990212],
        ...,
        [32.36990212, 31.7881303 , 31.22698167, ..., 31.22698167,
         31.7881303 , 32.36990212],
        [32.91156951, 32.33954348, 31.7881303 , ..., 31.7881303 ,
         32.33954348, 32.91156951],
        [33.47382175, 32.91156951, 32.36990212, ..., 32.36990212,
         32.91156951, 33.47382175]],

       [[32.91156951, 32.33954348, 31.7881303 , ..., 31.7881303 ,
         32.33954348, 32.91156951],
        [32.33954348, 31.75721551, 31.19551078, ..., 31.19551078,
         31.75721551, 32.33954348],
        [31.7881303 , 31.19551078, 30.62350485, ..., 30.62350485,
         31.19551078, 31.7881303 ],
        ...,
        [31.7881303 , 31.19551078, 30.62350485, ..., 3

In [8]:
px2.evaluate(orb2.theta2, orb2.phi2)

array([[[0.28191095+0.j, 0.28665879+0.j, 0.29144853+0.j, ...,
         0.29144853+0.j, 0.28665879+0.j, 0.28191095+0.j],
        [0.28677133+0.j, 0.29191261+0.j, 0.29687823+0.j, ...,
         0.29687823+0.j, 0.29191261+0.j, 0.28677133+0.j],
        [0.29141905+0.j, 0.29685578+0.j, 0.3021052 +0.j, ...,
         0.3021052 +0.j, 0.29685578+0.j, 0.29141905+0.j],
        ...,
        [0.40085129+0.j, 0.4083296 +0.j, 0.41555025+0.j, ...,
         0.41555025+0.j, 0.4083296 +0.j, 0.40085129+0.j],
        [0.40484415+0.j, 0.41210226+0.j, 0.41911239+0.j, ...,
         0.41911239+0.j, 0.41210226+0.j, 0.40484415+0.j],
        [0.40880734+0.j, 0.41569233+0.j, 0.42263806+0.j, ...,
         0.42263806+0.j, 0.41569233+0.j, 0.40880734+0.j]],

       [[0.27199408+0.j, 0.27687044+0.j, 0.28158018+0.j, ...,
         0.28158018+0.j, 0.27687044+0.j, 0.27199408+0.j],
        [0.27674299+0.j, 0.28191095+0.j, 0.28691364+0.j, ...,
         0.28691364+0.j, 0.28191095+0.j, 0.27674299+0.j],
        [0.28166254+0.j, 